### ISSUE TITLE
If the value of the old PATH lacks a trailing path separator, its new value becomes corrupt (the two last components simply concatenated).

### ISSUE THREAD

**Issue by k-j-kleist** [aaronpowell/ps-nvmw#63]
https://github.com/aaronpowell/ps-nvm/blob/b15c9259d069b30296f46edc91beb72f8aec9076/nvm.psm1#L122

Suggested fix:

`$persistedPaths = $persistedPaths + [System.IO.Path]::PathSeparator + $_`

An even better fix would avoid empty PATH components due to two succesive path separators (";;" / "::"), which will be the result of the suggested fix if the old PATH value _does_ have a trailing path separator.

I believe that on Windows, empty PATH components are harmless; while on some POSIX systems, they equal ".", the current working directory, which could potentially be dangerous.

**Comment by aaronpowell** [comment]
The code that I had to do the path persisting was not particularly well written. I've just done a small rewrite of it to make it a bit more functional (rather than procedural) that should also negate the chance of this problem happening by using `Where-Object` to filter the path down rather than `ForEach-Object` to try and create it on the fly.

I think there's probably still a possibility of it being broken but only if your existing path is already broken.

**Comment by aaronpowell** [comment]
This is merged and released as `2.0.2`.
